import { useState } from "react";
import { Link, Navigate, useLocation, useNavigate } from "react-router-dom";
import { Eye, EyeOff, Video, UploadCloud } from "lucide-react";
import toast from "react-hot-toast";
import { register as registerApi } from "../api/users";
import { useAuth } from "../context/AuthContext";
import { Button, Input } from "../components/ui";

function AuthShell({ children, title, subtitle, mode }) { return <main className="auth-page auth-minimal"><header className="auth-topbar"><Link to="/" className="brand"><span className="brand-mark"><Video size={18}/></span>vid<span>tube</span></Link><span className="auth-top-note">Watch what moves you.</span></header><section className="auth-panel"><div className="auth-card"><div className="auth-heading"><span className="eyebrow">{mode === "login" ? "SIGN IN TO VIDTUBE" : "CREATE YOUR ACCOUNT"}</span><h2>{title}</h2><p>{subtitle}</p></div>{children}<p className="auth-switch">{mode === "login" ? "New to Vidtube?" : "Already have an account?"} <Link to={mode === "login" ? "/register" : "/login"}>{mode === "login" ? "Create an account" : "Sign in"}</Link></p></div></section><footer className="auth-footer">Vidtube <span>·</span> Video, made for you</footer></main>; }

export function LoginPage() { const { user, login } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const [form, setForm] = useState({ identity: "", password: "" }); const [show, setShow] = useState(false); const [loading, setLoading] = useState(false); if (user) return <Navigate to={location.state?.from || "/"} replace/>; const submit = async (e) => { e.preventDefault(); if (!form.identity.trim() || !form.password) return toast.error("Enter your username or email and password"); setLoading(true); try { await login({ [form.identity.includes("@") ? "email" : "username"]: form.identity.trim(), password: form.password }); toast.success("Welcome back!"); navigate(location.state?.from || "/", { replace: true }); } catch (err) { toast.error(err.response?.data?.message || "Could not sign in"); } finally { setLoading(false); } }; return <AuthShell mode="login" title="Welcome back" subtitle="Pick up right where you left off."><form className="auth-form" onSubmit={submit}><Input label="Username or email" autoComplete="username" value={form.identity} onChange={(e) => setForm({ ...form, identity: e.target.value })} placeholder="you@example.com"/><label className="field"><span>Password</span><div className="password-wrap"><input className="input" type={show ? "text" : "password"} value={form.password} autoComplete="current-password" onChange={(e) => setForm({ ...form, password: e.target.value })} placeholder="Enter your password"/><button type="button" aria-label={show ? "Hide password" : "Show password"} onClick={() => setShow(!show)}>{show ? <EyeOff size={18}/> : <Eye size={18}/>}</button></div></label><Button type="submit" fullWidth loading={loading}>Sign in</Button></form></AuthShell>; }

export function RegisterPage() { const { user } = useAuth(); const navigate = useNavigate(); const [form, setForm] = useState({ fullName: "", username: "", email: "", password: "" }); const [avatar, setAvatar] = useState(null); const [cover, setCover] = useState(null); const [loading, setLoading] = useState(false); if (user) return <Navigate to="/" replace/>; const submit = async (e) => { e.preventDefault(); if (Object.values(form).some((v) => !v.trim()) || !avatar) return toast.error("Complete all required fields and choose an avatar"); if (!/^\S+@\S+\.\S+$/.test(form.email)) return toast.error("Enter a valid email address"); if (form.password.length < 6) return toast.error("Password must be at least 6 characters"); const data = new FormData(); Object.entries(form).forEach(([k, v]) => data.append(k, v)); data.append("avatar", avatar); if (cover) data.append("coverImage", cover); setLoading(true); try { await registerApi(data); toast.success("Account created — sign in to continue"); navigate("/login"); } catch (err) { toast.error(err.response?.data?.message || "Could not create account"); } finally { setLoading(false); } }; return <AuthShell mode="register" title="Create your account" subtitle="A great watch starts with a great community."><form className="auth-form" onSubmit={submit}><Input label="Full name" value={form.fullName} onChange={(e) => setForm({ ...form, fullName: e.target.value })} placeholder="Your name"/><Input label="Username" value={form.username} onChange={(e) => setForm({ ...form, username: e.target.value })} placeholder="Choose a username"/><Input label="Email" type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="you@example.com"/><Input label="Password" type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} placeholder="At least 6 characters"/><div className="file-picks"><label><UploadCloud size={18}/><span>Avatar <small>{avatar?.name || "Required"}</small></span><input type="file" accept="image/*" onChange={(e) => setAvatar(e.target.files?.[0])}/></label><label><UploadCloud size={18}/><span>Cover image <small>{cover?.name || "Optional"}</small></span><input type="file" accept="image/*" onChange={(e) => setCover(e.target.files?.[0])}/></label></div><Button type="submit" fullWidth loading={loading}>Create account</Button></form></AuthShell>; }
